version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    networks:
      - goals-net
    

  backend:
    container_name: backend-spring-app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - ./backend/testng.xml:/app/testng.xml
    environment:
      - spring.datasource.url=jdbc:sqlserver://mssql:1433;databaseName=SportFieldSchedulingSystem;encrypt=true;trustServerCertificate=true;
    depends_on:
      - mssql
    networks:
      - goals-net
  

  # frontend:
  #   stdin_open: true
  #   tty: true
  #   container_name: frontend-react-app
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - ./frontend/package.json:/app/package.json
  #     - ./frontend/package-lock.json:/app/package-lock.json
  #   depends_on:
  #     - backend
  #   networks:
  #     - goals-net

networks:
  goals-net:


      
  
  